"""Labelled customer profiles from 4.md — shared by dataset generation and validation."""

HIGH_CHURN = {
    "Tenure": 2,
    "PreferredLoginDevice": "Mobile Phone",
    "CityTier": 3,
    "WarehouseToHome": 38,
    "PreferredPaymentMode": "Cash on Delivery",
    "Gender": "Male",
    "HourSpendOnApp": 0,
    "NumberOfDeviceRegistered": 6,
    "PreferedOrderCat": "Mobile Phone",
    "SatisfactionScore": 1,
    "MaritalStatus": "Single",
    "NumberOfAddress": 7,
    "Complain": 1,
    "OrderAmountHikeFromlastYear": 10,
    "CouponUsed": 0,
    "OrderCount": 1,
    "DaySinceLastOrder": 45,
    "CashbackAmount": 18.0,
    "TotalSpend": 220.0,
    "AvgOrderValue": 220.0,
    "ReturnRate": 0.65,
    "CustomerAge": 24,
    "LastLoginDaysAgo": 50,
    "ReviewsGiven": 0,
    "WishlistItems": 0,
    "SubscriptionPlan": "Free",
    "ReferralsMade": 0,
    "SupportTicketCount": 8,
}

MODERATE_CHURN = {
    "Tenure": 12,
    "PreferredLoginDevice": "Mobile Phone",
    "CityTier": 2,
    "WarehouseToHome": 22,
    "PreferredPaymentMode": "Debit Card",
    "Gender": "Female",
    "HourSpendOnApp": 2,
    "NumberOfDeviceRegistered": 3,
    "PreferedOrderCat": "Fashion",
    "SatisfactionScore": 3,
    "MaritalStatus": "Married",
    "NumberOfAddress": 3,
    "Complain": 0,
    "OrderAmountHikeFromlastYear": 16,
    "CouponUsed": 4,
    "OrderCount": 5,
    "DaySinceLastOrder": 18,
    "CashbackAmount": 110.0,
    "TotalSpend": 2800.0,
    "AvgOrderValue": 560.0,
    "ReturnRate": 0.20,
    "CustomerAge": 31,
    "LastLoginDaysAgo": 14,
    "ReviewsGiven": 2,
    "WishlistItems": 6,
    "SubscriptionPlan": "Silver",
    "ReferralsMade": 1,
    "SupportTicketCount": 3,
}

LOW_CHURN = {
    "Tenure": 48,
    "PreferredLoginDevice": "Computer",
    "CityTier": 1,
    "WarehouseToHome": 10,
    "PreferredPaymentMode": "Credit Card",
    "Gender": "Female",
    "HourSpendOnApp": 5,
    "NumberOfDeviceRegistered": 2,
    "PreferedOrderCat": "Grocery",
    "SatisfactionScore": 5,
    "MaritalStatus": "Married",
    "NumberOfAddress": 2,
    "Complain": 0,
    "OrderAmountHikeFromlastYear": 25,
    "CouponUsed": 18,
    "OrderCount": 16,
    "DaySinceLastOrder": 3,
    "CashbackAmount": 310.0,
    "TotalSpend": 11500.0,
    "AvgOrderValue": 718.0,
    "ReturnRate": 0.02,
    "CustomerAge": 38,
    "LastLoginDaysAgo": 1,
    "ReviewsGiven": 12,
    "WishlistItems": 24,
    "SubscriptionPlan": "Platinum",
    "ReferralsMade": 8,
    "SupportTicketCount": 0,
}

LOYAL_WITH_COMPLAINT = {
    "Tenure": 36,
    "PreferredLoginDevice": "Computer",
    "CityTier": 1,
    "WarehouseToHome": 12,
    "PreferredPaymentMode": "Credit Card",
    "Gender": "Male",
    "HourSpendOnApp": 4,
    "NumberOfDeviceRegistered": 2,
    "PreferedOrderCat": "Electronics",
    "SatisfactionScore": 3,
    "MaritalStatus": "Married",
    "NumberOfAddress": 2,
    "Complain": 1,
    "OrderAmountHikeFromlastYear": 20,
    "CouponUsed": 12,
    "OrderCount": 10,
    "DaySinceLastOrder": 7,
    "CashbackAmount": 240.0,
    "TotalSpend": 8200.0,
    "AvgOrderValue": 820.0,
    "ReturnRate": 0.10,
    "CustomerAge": 45,
    "LastLoginDaysAgo": 3,
    "ReviewsGiven": 6,
    "WishlistItems": 14,
    "SubscriptionPlan": "Gold",
    "ReferralsMade": 4,
    "SupportTicketCount": 2,
}

VALIDATION_CASES = {
    "HIGH_CHURN": HIGH_CHURN,
    "MODERATE_CHURN": MODERATE_CHURN,
    "LOW_CHURN": LOW_CHURN,
    "LOYAL_W_COMPLAINT": LOYAL_WITH_COMPLAINT,
}

# Target P(churn) for synthetic anchor rows around each profile
ANCHOR_CHURN_PROB = {
    "HIGH_CHURN": 0.94,
    "MODERATE_CHURN": 0.43,
    "LOW_CHURN": 0.04,
    "LOYAL_W_COMPLAINT": 0.41,
}
